apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
spec:
  selector:
    matchLabels:
      app: node-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
        - image: danielnaumau/node-backend:test
          name: node-backend
          ports:
            - containerPort: 8080